title: Kiro Guide
description: Community guide to Kiro IDE, Chat, and CLI
baseurl: "/kiro-guide"
url: "https://sandikodev.github.io"

theme: just-the-docs

# Search
search_enabled: true
search_tokenizer_separator: /[\s\-/]+/

# Navigation
nav_sort: case_insensitive

# Footer
footer_content: "MIT License &copy; 2026 <a href=\"https://github.com/sandikodev\">sandikodev</a> and contributors."

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/sandikodev/kiro-guide"

aux_links_new_tab: true

# Back to top
back_to_top: true
back_to_top_text: "Back to top"

# Callouts
callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
